# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI-CD Databricks

on:
  push:
    branches: [ main, qas, dev ]
    paths: ['**.py']
  #push:
  #  branches: [ main ]

jobs:
  dev:
    
    runs-on: ubuntu-latest
    environment: 
      name: dev
      
    env:
      DBKS_HOST:  ${{ secrets.DBKS_HOST }}
      DBKS_TOKEN: ${{ secrets.DBKS_TOKEN }}
      
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

      # pip install flake8 pytest
      # if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: install-databricks-cli
      uses: microsoft/install-databricks-cli@v1.0.0
 
    # Import notebook to Shared
    - name: Import local github directory to Shared
      run: databricks workspace import_dir --overwrite . /Shared

    # List Shared content
    - name: List workspace with databricks CLI
      run: databricks workspace list --absolute --long --id /Shared


#    - name: Test with pytest
#      run: |
#        pytest
