name : Setup Databricks Jobs.  
on : 
  push :
    branches : ['dev', 'qas', 'stg', 'prd']

env :
  GH_REPO    : Bineo2/data-cx-collections-upload
  ENV_BRANCH : ${{github.base_ref || github.ref_name}}

jobs :
  build-and-deploy : 
    runs-on     : ubuntu-latest
    environment : ${{github.base_ref || github.ref_name}}
    
    steps :    
    - name : Checkout GitHub Actions 
      uses : actions/checkout@v2
      with : 
        repository : ${{env.GH_REPO}}
        ref        : ${{env.ENV_BRANCH}}

    # https://github.com/mr-smithers-excellent/docker-build-push
    - name : Docker registry, build and push
      id   : container-registry
      uses : mr-smithers-excellent/docker-build-push@v5.5
      with : 
        registry   : ${{secrets.ACR_USER}}.azurecr.io
        username   : ${{secrets.ACR_USER}}
        password   : ${{secrets.ACR_PASS}}
        image      : ${{env.DKR_IMAGE}}
        tags       : ${{env.DKR_TAG}}
        dockerfile : dockerfile.ci 
        buildArgs  : SERVER_TYPE=wap,ENV_TYPE=${{env.ENV_BRANCH}}
        
    - name : Deploy to App Service
      uses : azure/webapps-deploy@v2
      with :
        images : "${{secrets.ACR_USER}}.azurecr.io/${{env.DKR_IMAGE}}:${{env.DKR_TAG}}"
        app-name : ${{env.WAP_NAME}}
        publish-profile : ${{secrets.WAP_PUBLISH}}
        
     
